import {
  create,
  NLayout, NLayoutContent, NLayoutFooter, NLayoutHeader, NLayoutSider,
  NSpace, NButton, NDivider, NIcon, NButtonGroup, NMessageProvider, NDropdown,
  NBreadcrumb, NBreadcrumbItem, NInput, NInputGroup, NTree, NDataTable,
  NUpload, NUploadTrigger, NUploadFileList, NCard, NModal,
} from 'naive-ui'

export default create({
  components: [
    NButton,
    NButtonGroup,
    NLayout,
    NLayoutHeader,
    NLayoutFooter,
    NLayoutContent,
    NLayoutSider,
    NSpace,
    NDivider,
    NIcon,
    NMessageProvider,
    NDropdown,
    NBreadcrumb,
    NBreadcrumbItem,
    NInput,
    NInputGroup,
    NTree,
    NDataTable,
    NUpload,
    NUploadTrigger,
    NUploadFileList,
    NCard,
    NModal,
  ],
})
